### ISSUE TITLE
Ability to view CV by a pop up.

### ISSUE THREAD

**Issue by tormod17** [hutosaha/hrns-#141]
Ability to view CV by a pop up jumping out on top of the page, so as to instantly decided whether to reject or accept, without downloading.

client/job/vid  page 

admin/job/vid page

**Comment by tormod17** [comment]
Added file viewer  to client page, problem with non-pdf files only pdf and Open Document  Format supported. 
Looking into converting all files to pdf . or saving files as open document format. 
http://viewerjs.org/examples/

**Comment by mk4111** [comment]
- [ ] Delete files - set expiry date?

**Comment by mk4111** [comment]
Hey @tormod17!
So I've pushed up my changes to the 'viewer' branch, and have made a pull request.

I've managed to do the conversion from (doc/docx files to pdf), and the files are being deleted on exiting the browser/going to another page. 

The files are being deleted just prior to exiting because the expiration/timeout method I was a bit more complex - I realised that the timer kept resetting on page (re)load. Could've saved the UTC time and compared instead, but you'd have to come onto that page to delete it (i.e. cookie check would only occur on that page) + it was extra functionality. Thought it might be worth mentioning in case you preferred that approach because it might be more elegant... 

Anyhoo, hope what I've done is ok!

**Comment by mk4111** [comment]
Also, I didn't get around to finishing refactoring public/js/clientjob.js from lines 103 to 279 (really sorry! I've got to leave my house in a jiffy!), but I've realised that there are two sets of the reject and accept functions - one set of which can totally be dropped! :D thought that was cool!!

**Comment by tormod17** [comment]
Great Stuff Marie enjoy your trip
