### ISSUE TITLE
Marketing site

### ISSUE THREAD

**Issue by carlstratton** [hutosaha/hrns-#160]
Hi Guys,

Please see attached the invision link to the revised marketing page, with a link to the copy and image below. Let me know if you need anything more from me.

Almost there! Sorry for any changes from this to the last version, it's basically all in the same place apart from the buttons, and we've added an About section to the bottom. Let me know when you're done and i'll dou le check the font sizes and stuff.

**Invision Link:**
https://projects.invisionapp.com/share/ZB76LCO8X#/screens/159227450_Desktop_Copy_2

**Copy**
https://drive.google.com/file/d/0B53z8E7uPDPSLUl3YkFRTFlBNzZ1bWFBclBoODFkdnRrMmY4/view?usp=sharing

![harness-hero-1024x620](https://cloud.githubusercontent.com/assets/1009195/15303351/3e131410-1baf-11e6-81a8-35b1178c336a.jpg)

@tormod17 @mk4111 @Benbrierley @joshbrierley

**Comment by tormod17** [comment]
@carlstratton cheers Carl a bit late in the day but will try to make changes.

**Comment by tormod17** [comment]
@carlstratton  do you have the icons and new background image as well as the  'about us text' as not able to copy and paste from your invision.  thanks

**Comment by carlstratton** [comment]
@tormod17 the copy (all text used in the invision image) and the background image are at the start of this thread? Let me know if you can't see them. Thanks

**Comment by Benbrierley** [comment]
@carlstratton @tormod17 shortened the "How It Works" sectio to even up the copy length in each stage.

1.	CLICK 
a.	Simply enter into Harness the vacancy you have, click Submit, and boom! The best tech recruiters around the world are working to find you the very best tech talent.
2.	SMILE
a.	Sit back, relax and watch the best candidates come your way – no admin, no chasing, we arrange interviews and do all the hard work, and so you don’t have too!
3.	HIRE
a.	Found someone perfect for your team? Hire them! Harness allows you to focus on the things you love doing; meeting and greeting amazing people for your team!

**Comment by Benbrierley** [comment]
@carlstratton we don't need both testimonials and "trusted by" - can we just keep "Trusted by" and replace testimonials with "Why Harness?" We need a small sell on the page, and could use those icons you put into the Pitch Deck?

**Comment by carlstratton** [comment]
@Benbrierley sure, can you send over the copy for 'Why Harness'?
@tormod17 Please don't work on this until we've got final sign off on the page. Apologies.
Cheers!

**Comment by Benbrierley** [comment]
Why Harness?

EASIER
All you do is enter who you need. Literally that's it. No endless cold calls, multiple recruiter briefings, candidate chasing, sending 100's of LinkedIn messages, trawling through CV boards... 
QUICKER
Harness requires you to do nothing but review high quality, relevant and available CV's in one simple place. Zero admin. We cut through the nonsense of recruiting, and free you up to do important stuff!
QUALITY
Where else can you guarantee every inch of the market has been scoured for the best tech talent? Our exclusive, curated network means no stone goes unturned in finding you the perfect candidate.
FLEXIBLE
Don't need to hire this month? Then don't pay! We only charge you when you need us. Think of us as your super in-house recruiter, we're there when you need us. Otherwise, we'll just be chilling.
FUN-ER
That's right, recruitment can be fun! We allow you to focus on the fun and important parts of hiring; meeting, greeting and qualifying the future employees of your business! No boring bits. Guaranteed.
VALUE
Recruiting the top 5% top tech talent doesn't have to cost the earth, we make sure of it. 90% of what you pay us only happens when you find the candidate you love! OMG. No seriously, it's true.


@carlstratton @tormod17  thoughts welcome

**Comment by carlstratton** [comment]
Hi All,

You'll see the revised prototype in the invision link below, also @tormod17 I've invited you to see the Zeplin sketch file, so you can take any CSS styles directly from that to make life easier. @Benbrierley I think this is working much better with the new icons, text and general flow. Good work. @joshbrierley @mk4111  

**Invision**
https://invis.io/ZB76LCO8X#/159611151_Harness_V5

**Zeplin**
https://zpl.io/1jlU6j

**SVG Icons**
[hrns_icons.zip](https://github.com/hutosaha/hrns-/files/269230/hrns_icons.zip)

![harness v5](https://cloud.githubusercontent.com/assets/1009195/15340574/faab1370-1c81-11e6-933a-382748e5e7bb.jpg)

**Comment by tormod17** [comment]
Great ,I'm hoping to give it a massive push today.  nearly there.

**Comment by carlstratton** [comment]
THAT'S THE SPIRIT! :)

Are you around for the meeting this evening?

Carl


*— *

t: 07824 632 199
e: cgstratton@gmail.com

senior UX designer at farfetch <http://www.farfetch.com>
co-founder | emblzn.com
designer | carlstratton.co.uk

**Comment by Benbrierley** [comment]
@carlstratton  LOVE IT! Great job! Few things though; it should say TRUSTED BY, not WHY HARNESS (in the section under the front top page)

Also, can we put a full stop after 

Find your human.

It has more impact?

**Comment by Benbrierley** [comment]
Also, @carlstratton is it best having no link to the recruiter explanation page? Is this too complex now @tormod17 if I write the copy?

**Comment by Benbrierley** [comment]
Also,@carlstratton can we add in a two cartoon pictures at the bottom of About Us,  one of me and J, and one of you? (I want to add some real human value into Harness by using the brother thing, people really buy real human stories)

**Comment by tormod17** [comment]
@Benbrierley @carlstratton Where is the link to the recruiter explanation page , I noticed an agency login  in the footer. @carlstratton  zeplin is pretty cool @Benbrierley Before we add more scope lets finish first. But no it should be too difficult.

**Comment by carlstratton** [comment]
Hey Tormod, can you see the link in the footer? That will be the link to
the agency page IF they get stuck. Ideally they shouldn't get that stuck!

Thanks,

Carl


*— *

t: 07824 632 199
e: cgstratton@gmail.com

senior UX designer at farfetch <http://www.farfetch.com>
co-founder | emblzn.com
designer | carlstratton.co.uk
