### ISSUE TITLE
Seperate out the 19 files in views into folders

### ISSUE THREAD

**Issue by shouston3** [hutosaha/hrns-#53]
Love the app, the user interface flow is really nice. Cant wait to see how it turns out.

It may make the view file more readable if you put failure, adminjob, candidate, logout, signupsuccess and unapproved into a 'static' folder as these files don't really have any meat in them and just clutter the views file

**Comment by hdrdavies** [comment]
Right you are @shouston3. At the end of last week we worked a little bit on separating some stuff out into partials - but more needs to be done. I guess if they were static files we could use ```reply.file``` rather than ```reply.view```... I'm not sure we can take files out of the views folder as because of the way handlebars is configured, I have a feeling all the views need to be in the same folder. Might well be wrong though. 

Will keep working on refactoring the front end code as per #56

**Comment by shouston3** [comment]
Cool, I originally opened this as I thought it may be a quick fix, but it sounds not worth the hassle to configure where handlebars looks for its 'views'
