### ISSUE TITLE
Set up AWS & Heroku accounts 

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#95]

**Comment by mk4111** [comment]
LinkedIn

**Comment by tormod17** [comment]
@Benbrierley  as per conversation on Friday tried to set you up on various accounts but didn't get into your linkedin and heroku needs a credit card to be registered to use the add on services that we require for the database and mail client. 
I reckon you'd be best setting up a harness linkedin account , and then registering an app via this, rather than using your personal one. If you want me to do this with you let me know a suitable time.
